language: node_js
node_js: 10
sudo: true

cache:
  directories:
    - node_modules

install:
  - sudo apt-get install -yq libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install --no-spin

script:
  - npm run build:production
  - npm run lint
  - npm test

notifications:
  email: false
  slack:
    secure: kTkyLd+WlJE/cm39pm9jAZ11+QA1JKl8/eiOtPc4hkqvucMrBZu6k8V+TBoqgahLeUj/nWSWxJJJYZcElB/eXFgDfPoEAm+zOM3EsCrOBnBY5HhpnlCp95dZAcRlPwuhmB8kYK6Yl8v/qzvofQjbf/Lmk62tvFtlk3+S5WKDXbY=
