language: node_js
install: npm install less && wget http://dl.google.com/closure-compiler/compiler-latest.zip && unzip compiler-latest.zip && chmod a+rx compiler.jar && ./build.sh all
script: phantomjs tests/run.js
